- name: Install NGINX
  hosts: aws_ec2
  become: true
  tasks:
    - name: Upgrade package manager
      apt:
        upgrade: yes
    - name: Update package manager
      shell: apt update --fix-missing


    - name: Install nginx
      apt:
        name: nginx
        state: present